language: python
python:
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install sh"
  - "git config --global user.email 'travis@xd-embedded.org'"
  - "git config --global user.name 'Travis CI'"
script: "nosetests"
after_success:
  - coveralls
notifications:
  irc: "chat.freenode.net#xd-embedded"
